export const FEATURES = [
  {
    id: 1,
    title: "AI Itinerary Builder",
    description: "Generate complete day-by-day travel plans in seconds using cutting-edge AI reasoning.",
    icon: "🗺️",
    color: "bg-emerald-500/15 border-emerald-500/20",
    tag: "Core",
  },
  {
    id: 2,
    title: "Smart Hotel & Flight Picks",
    description: "Personalized accommodation and flight recommendations matched to your budget and style.",
    icon: "✈️",
    color: "bg-amber-500/15 border-amber-500/20",
    tag: "Booking",
  },
  {
    id: 3,
    title: "Real-Time Trip Alerts",
    description: "Never miss a check-in, flight, or experience with intelligent push reminders.",
    icon: "🔔",
    color: "bg-indigo-500/15 border-indigo-500/20",
    tag: "Smart",
  },
  {
    id: 4,
    title: "Conversational AI Agent",
    description: "Refine every detail of your trip through natural conversation with your RoamIQ assistant.",
    icon: "🤖",
    color: "bg-emerald-500/15 border-emerald-500/20",
    tag: "AI",
  },
  {
    id: 5,
    title: "Climate-Aware Packing",
    description: "Smart packing lists generated from live weather data and your destination's seasonal patterns.",
    icon: "🌤️",
    color: "bg-amber-500/15 border-amber-500/20",
    tag: "New",
  },
  {
    id: 6,
    title: "Budget Intelligence",
    description: "Granular cost estimates and live currency conversion for every aspect of your journey.",
    icon: "💰",
    color: "bg-indigo-500/15 border-indigo-500/20",
    tag: "Finance",
  },
  {
    id: 7,
    title: "Offline Travel Docs",
    description: "Download your full itinerary, tickets, and maps as a single PDF for use without internet.",
    icon: "📄",
    color: "bg-emerald-500/15 border-emerald-500/20",
    tag: "New",
  },
  {
    id: 8,
    title: "Group Trip Sync",
    description: "Collaborate on a shared itinerary with your travel companions in real-time.",
    icon: "👥",
    color: "bg-amber-500/15 border-amber-500/20",
    tag: "Social",
  },
  {
    id: 9,
    title: "Local Hidden Gems",
    description: "AI-curated secret spots, local eateries, and off-the-beaten-path experiences for every city.",
    icon: "💎",
    color: "bg-indigo-500/15 border-indigo-500/20",
    tag: "Discovery",
  },
];

export const DESTINATIONS = [
  {
    id: "paris",
    name: "Paris",
    country: "France",
    tag: "Romantic",
    gradient: "from-blue-900 via-indigo-900 to-purple-900",
    image: "/paris.jpg",
    size: "tall",
    desc: "City of light & love",
  },
  {
    id: "bali",
    name: "Bali",
    country: "Indonesia",
    tag: "Tropical",
    gradient: "from-teal-900 via-emerald-900 to-green-900",
    image: "/bali.png",
    size: "small",
    desc: "Island of the gods",
  },
  {
    id: "tokyo",
    name: "Tokyo",
    country: "Japan",
    tag: "Cultural",
    gradient: "from-pink-900 via-rose-900 to-purple-900",
    image: "/tokyo.jpg",
    size: "small",
    desc: "Neon & tradition",
  },
  {
    id: "new-york",
    name: "New York",
    country: "USA",
    tag: "Urban",
    gradient: "from-gray-900 via-slate-900 to-zinc-900",
    image: "/new-york.png",
    size: "small",
    desc: "The city that never sleeps",
  },
  {
    id: "dubai",
    name: "Dubai",
    country: "UAE",
    tag: "Luxury",
    gradient: "from-amber-900 via-orange-900 to-yellow-950",
    image: "/dubai.png",
    size: "small",
    desc: "Opulence redefined",
  },
];

export const MOCK_PLAN = {
  summary: {
    budgetBreakdown: [
      { category: "Flights", amount: 1200 },
      { category: "Accommodation", amount: 2500 },
      { category: "Activities", amount: 800 },
      { category: "Food & Transport", amount: 1000 },
    ],
  },
  itinerary: [
    {
      day: 1,
      title: "Arrival & First Impressions",
      morning: "Touch down and check into your handpicked boutique stay. Take a slow walk to shake off jet lag.",
      afternoon: "Guided walking tour of the old quarter — discover local squares and hidden alleys the guidebooks miss.",
      evening: "Rooftop dinner overlooking the illuminated skyline. Toast to the adventure ahead.",
      lunch: "Café du Marché — seasonal plates and house-made bread.",
      dinner: "Altitude Lounge — contemporary farm-to-fork fine dining.",
      spend: "$160",
      tips: "Grab a local SIM at the airport — data is cheap and maps will be your best friend.",
    },
    {
      day: 2,
      title: "Culture & Craft",
      morning: "Beat the crowds at the National Museum with early-entry tickets. Linger in the ancient gallery.",
      afternoon: "Join a hands-on artisan workshop — try your hand at traditional pottery or textile weaving.",
      evening: "Jazz club evening or open-air opera in the cultural quarter.",
      lunch: "The Atelier Café — light mezze and seasonal salads.",
      dinner: "Heritage Table — seven-course tasting menu with local wine pairings.",
      spend: "$210",
      tips: "Pre-book museum tickets 48 hours ahead — sold out slots are common on weekends.",
    },
    {
      day: 3,
      title: "Markets, Parks & Sunset Cruise",
      morning: "Wander the central market at golden hour. Sample street food and meet local vendors.",
      afternoon: "Cycle through the botanical gardens and along the scenic riverside paths.",
      evening: "Private sunset boat cruise with acoustic music and local wine tasting.",
      lunch: "Market Stall Crawl — a curated tasting of five legendary street-food spots.",
      dinner: "The Dock — freshly caught seafood with harbour views.",
      spend: "$135",
      tips: "Wear comfortable shoes and bring a reusable tote — the market vendors love that.",
    },
  ],
  bookings: {
    flights: [
      { airline: "SkyBridge Air", price: "$820", duration: "11h 50m", type: "Direct" },
      { airline: "GlobalHop Connect", price: "$640", duration: "14h 20m", type: "1 Stop" },
      { airline: "Prestige Wings", price: "$1,090", duration: "10h 55m", type: "Business" },
    ],
    hotels: [
      { name: "The Meridian Collection", stars: 5, price: "$340/night", reason: "Matches your Luxury style — private spa, rooftop pool, and 24-hr concierge." },
      { name: "Nomad House Suites", stars: 4, price: "$195/night", reason: "Central location with a co-working lounge, great for remote workers." },
      { name: "Garden & Grove Retreat", stars: 4.5, price: "$265/night", reason: "Ideal for Relaxation — a quiet garden district with forest-bathing sessions." },
    ],
    activities: [
      { name: "Private Food & Market Tour", cost: "$90", icon: "🍴" },
      { name: "VIP Museum Early Access", cost: "$50", icon: "🏛️" },
      { name: "Sunset Catamaran Charter", cost: "$130", icon: "⛵" },
    ],
  },
  checklist: [
    { title: "Visa Requirements", content: "eVisa required. Apply online at least 7 days before departure — processing is typically 48 hours.", icon: "🛂" },
    { title: "Best Booking Window", content: "Flights are 20–35% cheaper when booked 6–8 weeks out. Set a price alert now.", icon: "📅" },
    { title: "Packing Essentials", content: "Light layers, a packable rain jacket, comfortable walking shoes, and a universal adapter.", icon: "🎒" },
    { title: "Currency & Payments", content: "Local currency preferred for markets and small restaurants. Cards accepted at hotels.", icon: "💳" },
    { title: "Health & Coverage", content: "Travel insurance is strongly advised. Check your destination's vaccination requirements 4 weeks out.", icon: "🛡️" },
  ],
};
